//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPRF
    {
        public int prfID { get; set; }
        public string workingStatus { get; set; }
        public string slabdetail { get; set; }
        public string slabheight { get; set; }
        public string plinthheight { get; set; }
        public string porchheight { get; set; }
        public string elevationpattern { get; set; }
        public string towerroom { get; set; }
        public string cornerplotplan { get; set; }
        public string plotside { get; set; }
        public string boundrywall { get; set; }
        public string anyother { get; set; }
        public string doorlintel { get; set; }
        public string windowsill { get; set; }
        public string windowlintel { get; set; }
        public long projectID { get; set; }
    
        public virtual tblProjectDetail tblProjectDetail { get; set; }
    }
}
