//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectUploadFile
    {
        public int uploadfileID { get; set; }
        public System.DateTime dt { get; set; }
        public Nullable<long> projectID { get; set; }
        public int designerID { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string filename { get; set; }
    
        public virtual tblProjectDetail tblProjectDetail { get; set; }
        public virtual tblStaff tblStaff { get; set; }
    }
}
