//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffLedger
    {
        public int staffLedgerID { get; set; }
        public System.DateTime dt { get; set; }
        public int staffID { get; set; }
        public int projectID { get; set; }
        public int prjAmount { get; set; }
        public int paidAmount { get; set; }
        public int balance { get; set; }
        public string remark { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
