//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStaff()
        {
            this.tblOperations = new HashSet<tblOperation>();
            this.tblStaffLedgers = new HashSet<tblStaffLedger>();
            this.tblStaffPaids = new HashSet<tblStaffPaid>();
            this.tblProjectUploadFiles = new HashSet<tblProjectUploadFile>();
        }
    
        public int staffID { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string dist { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string emailID { get; set; }
        public string rolltype { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOperation> tblOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStaffLedger> tblStaffLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStaffPaid> tblStaffPaids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectUploadFile> tblProjectUploadFiles { get; set; }
    }
}
