//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public tblClient()
        {
            this.tblAmountReceive = new HashSet<tblAmountReceive>();
            this.tblProjectDetail = new HashSet<tblProjectDetail>();
        }
    
        public int clientID { get; set; }
        public string clientName { get; set; }
        public string orgName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string emailID { get; set; }
        public string remark { get; set; }
    
        public virtual ICollection<tblAmountReceive> tblAmountReceive { get; set; }
        public virtual ICollection<tblProjectDetail> tblProjectDetail { get; set; }
    }
}
