//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDesignEntities : DbContext
    {
        public SDesignEntities()
            : base("name=SDesignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAmountReceive> tblAmountReceive { get; set; }
        public virtual DbSet<tblClient> tblClient { get; set; }
        public virtual DbSet<tblOperation> tblOperation { get; set; }
        public virtual DbSet<tblProjectDetail> tblProjectDetail { get; set; }
        public virtual DbSet<tblSfaff> tblSfaff { get; set; }
        public virtual DbSet<tblStaffPaid> tblStaffPaid { get; set; }
    }
}
