//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDetail
    {
        public tblProjectDetail()
        {
            this.tblOperation = new HashSet<tblOperation>();
            this.tblStaffPaid = new HashSet<tblStaffPaid>();
        }
    
        public int projectID { get; set; }
        public System.DateTime dt { get; set; }
        public int clientID { get; set; }
        public string projectType { get; set; }
        public string projectLevel { get; set; }
        public string package { get; set; }
        public string plotSize { get; set; }
        public int amount { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual ICollection<tblOperation> tblOperation { get; set; }
        public virtual ICollection<tblStaffPaid> tblStaffPaid { get; set; }
    }
}
