//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchManagerDBEntities : DbContext
    {
        public ArchManagerDBEntities()
            : base("name=ArchManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAmountReceive> tblAmountReceives { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblClientLedger> tblClientLedgers { get; set; }
        public virtual DbSet<tblCompanyProfile> tblCompanyProfiles { get; set; }
        public virtual DbSet<tblGmailAccount> tblGmailAccounts { get; set; }
        public virtual DbSet<tblOperation> tblOperations { get; set; }
        public virtual DbSet<tblPRF> tblPRFs { get; set; }
        public virtual DbSet<tblProfile> tblProfiles { get; set; }
        public virtual DbSet<tblProjectDetail> tblProjectDetails { get; set; }
        public virtual DbSet<tblStaff> tblStaffs { get; set; }
        public virtual DbSet<tblStaffLedger> tblStaffLedgers { get; set; }
        public virtual DbSet<tblStaffPaid> tblStaffPaids { get; set; }
        public virtual DbSet<tblStatu> tblStatus { get; set; }
    }
}
