//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdminSetting
    {
        public int adminSettingiD { get; set; }
        public int companyID { get; set; }
        public long projectID { get; set; }
        public string projectPrefix { get; set; }
        public Nullable<int> quotationID { get; set; }
        public string quotationPrefix { get; set; }
    
        public virtual tblCompanyProfile tblCompanyProfile { get; set; }
    }
}
