//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDetailItem
    {
        public int projectDetailItemID { get; set; }
        public long projectID { get; set; }
        public string projectDetail { get; set; }
        public string service { get; set; }
        public string area { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual tblProjectDetail tblProjectDetail { get; set; }
    }
}
