//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectManagement
    {
        public int pmID { get; set; }
        public System.DateTime dt { get; set; }
        public long projectID { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string projectstatus { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
        public string User_UploadedFileName { get; set; }
    
        public virtual tblProjectDetail tblProjectDetail { get; set; }
    }
}
