//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationItem
    {
        public int quotationItemID { get; set; }
        public int quotationID { get; set; }
        public string projectDescription { get; set; }
        public string service { get; set; }
        public string hsn { get; set; }
        public int qty { get; set; }
        public string prjUnit { get; set; }
        public int rate { get; set; }
        public int amount { get; set; }
    
        public virtual tblQuotation tblQuotation { get; set; }
    }
}
