//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotation()
        {
            this.tblQuotationItems = new HashSet<tblQuotationItem>();
            this.tblProjectDetails = new HashSet<tblProjectDetail>();
        }
    
        public int quotationID { get; set; }
        public int quotationNo { get; set; }
        public System.DateTime dt { get; set; }
        public string projectName { get; set; }
        public string services { get; set; }
        public int total { get; set; }
        public string remark { get; set; }
        public int clientID { get; set; }
        public string status { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationItem> tblQuotationItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectDetail> tblProjectDetails { get; set; }
    }
}
