//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSDesign.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubcategory
    {
        public int subcategoryID { get; set; }
        public int categoryID { get; set; }
        public string subcateroyName { get; set; }
        public bool status { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
